// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcrwnuupxxofljsquvog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjcndudXVweHhvZmxqc3F1dm9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NzQ4ODMsImV4cCI6MjA3NDQ1MDg4M30.VeGTy7DCMvc7MvSPoKdNTketYxEyZK1d1rYa186PjvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});